%% Script: Genetic Algorithm Optimization
%
% Author: Elia Matsumoto
% Fonte: SPTech School
%
% Contact: elia.matsumoto@fgv.br
%
%% Reseting environment
rng('shuffle'); % Random seed
close all       % Close all figure
clear           % Clear workspace
clc             % Clear command window

%% Words
words = [ "não" "sim" "que" "para" "isso" "esse" "por" ...
    "sua" "seu" "ele" "ela" "eles" "elas" "aqui" ...
    "está" "você" "uma" "com" "coisa" "mas" "vou" ...
    "ser" "estar" "como" "nós" "até" "meu" "minha" ...
    "vai" "onde" "mim" "todos" "tudo" "isso" "nisso" ...
    "estou" "nos" "acho" "acha" "qual" "nada" ...
    "chewie" "ficar" "luke" "mesmo" "princesa" ...
    "tenho" "jabba" "garoto" "sobre" "agora" "mais" ...
    "muito" "vamos" "obiwan" "ajudeme" "kenobi" ...
    "vader" "dantooine" "vêm" "alderaan" "tem" "nossa" ...
    "quando" "estão" "ainda" "desta" "parece" "ter" ...
    "threepio" "quem" "ben" "então" "owen" "foi" "esses" ...
    "droide" "algo" "biggs" "pode" "tio" "fazer" "tão" ...
    "artoo" "senhor" "sou" "nosso" "essa" "apenas" ...
    "diz" "disso" "indo" "deve" "são" "sei" "dele" "este" ...
    "alguma" "também" "entendo" "artoodetoo" "fui" "quê" ...
    "vez" "comigo" "envio" "navio" "envie" "alteza" "algum" ...
    "foram" "fique" "seus" "sinto" "quero" "skywalker" ...
    "almirante" "lando" "dizer" "vejo" "daqui" "dar" ...
    "toda" "gás" "viu" "outra" "três" "dos" "hein" "leia" ...
    "todo" "fett" "yoda" "dagobah" "han" "dack" "rouge" ...
    "ver" "wedge" "procurando" "fazendo" "estamos" ...
    "posso" "jedi" "solo" "será" "levar" "dois" "deles" ...
    "droides" "darth" "meus" "encontrar" "seja" "calrissian" ...
    "podemos" "piett" "falcon" "juntese" "esta" "millennium" ...
    "suas" "possa" "talvez" "parafuso" "nem" "nessa" ...
    "diga" "essas" "coisas" "chewbacca" "hiperdrive" ...
    "computador" "minhas" "shoo" "ouça" "volte" ...
    "acomplamento" "virese" "asteróides" "mestre" ...
    "ohhh" "hutt" "lhe" "vão" "disse" "olá" "espere" ...
    "das" "the" "seis" "sarlacc" "cinco" "formas"...
    "cima" "acontecendo"];

%% Initialization
episode = {'IV' 'V' 'VI'};
Name = {'HAN' 'LEIA' 'LUKE' 'THREEPIO' 'VADER'};

%% For all episodes
for i = 1:length(episode)
    %% Read file
    filename = ['SW_Episode' episode{i} '_ptBR.txt'];
    tbl = readtable(filename,"TextType","string");

    %% For all characters Character
    for j=1:length(Name)
        idx  = tbl.Var2 == Name{j};
        BagName = tokenizedDocument(lower(tbl.Var3(idx)));

        %% Ponctuation
        BagName = erasePunctuation(BagName);

        %% Less than 2 letters
        BagName = removeShortWords(BagName,2);


        BagName = removeWords(BagName,words);
        figure;
        wordcloud(BagName);
        title(['Episódio: ' episode{i} ' Personagem: ' Name{j}]);

        %% Outpufile
        word_list = cellstr(BagName.Vocabulary');
        word_list = ['Palavras' ; word_list];
        outfile = ['SW_Episode' episode{i}  '_' Name{j} '.csv'];
        writecell(word_list,outfile);
    end
end
